# -*- coding: utf-8 -*-
"""ML_PROJECT_1_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOxrWK0P7c3WzG9Uaa3Y9v88_vDkzrAs

**Heart Disease Prediction using Machine Learning**

Heart disease can be predicted based on various symptoms such as age, gender, heart rate, etc. and reduces the death rate of heart patients.

Due to the increasing use of technology and data collection, we can now predict heart disease using machine learning algorithms. Now let’s go further with the task of heart disease prediction using machine learning with Python.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# %matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

df = pd.read_csv("heart_disease_dataset.csv")
df.head()

pd.set_option("display.float", "{:.2f}".format)
df.describe()

df.target.value_counts().plot(kind="bar", color=["salmon", "lightblue"])

"""**We have 165 people with heart disease and 138 people without heart disease, so our problem is balanced.**"""

# Checking for messing values
df.isna().sum()

# This dataset looks perfect to use as we don’t have null values.

categorical_val = []
continous_val = []
for column in df.columns:
    print('==============================')
    print(f"{column} : {df[column].unique()}")
    if len(df[column].unique()) <= 10:
        categorical_val.append(column)
    else:
        continous_val.append(column)

plt.figure(figsize=(15, 15))

for i, column in enumerate(categorical_val, 1):
    plt.subplot(3, 3, i)
    df[df["target"] == 0][column].hist(bins=35, color='blue', label='Have Heart Disease = NO', alpha=0.6)
    df[df["target"] == 1][column].hist(bins=35, color='red', label='Have Heart Disease = YES', alpha=0.6)
    plt.legend()
    plt.xlabel(column)

"""**🔍 Observations from the Plot**

1. **cp (Chest pain):**
People with cp = 1, 2, 3 are more likely to have heart disease compared to cp = 0.

2. **restecg (Resting EKG results):**
People with restecg = 1 (abnormal heart rhythm) are more likely to have heart disease.

3. **exang (Exercise-induced angina):**
People with exang = 0 (No angina during exercise) have more heart disease than those with exang = 1 (Yes).

4. **slope (Slope of ST segment during peak exercise):**
People with slope = 2 (Downsloping) are more likely to have heart disease.
Compared to:
**0 (Upsloping) → healthier heart**
**1 (Flat) → minimal change, generally normal**

5. **ca (Number of major vessels (0-3) stained by fluoroscopy):**
Lower value is worse → People with ca = 0 are more likely to have heart disease.

6. **thal (Thalium stress result):**
People with thal = 2 (corrected defect) are more likely to have heart disease.
"""

plt.figure(figsize=(15, 15))

for i, column in enumerate(continous_val, 1):
    plt.subplot(3, 2, i)
    df[df["target"] == 0][column].hist(bins=35, color='blue', label='Have Heart Disease = NO', alpha=0.6)
    df[df["target"] == 1][column].hist(bins=35, color='red', label='Have Heart Disease = YES', alpha=0.6)
    plt.legend()
    plt.xlabel(column)

"""### 🔍 Observations from the Plot

* **trestbps:**

  * Resting blood pressure anything above **130–140** is generally of concern.

* **chol:**

  * Greater than **200** is of concern.

* **thalach:**

  * People with a maximum of over **140** are more likely to have heart disease.

* **oldpeak:**

  * The old peak of exercise-induced ST depression vs. rest looks at heart stress during exercise; an unhealthy heart will stress more.

"""

# Create another figure
plt.figure(figsize=(10, 8))

# Scatter with postivie examples
plt.scatter(df.age[df.target==1],
            df.thalach[df.target==1],
            c="salmon")

# Scatter with negative examples
plt.scatter(df.age[df.target==0],
            df.thalach[df.target==0],
            c="lightblue")

# Add some helpful info
plt.title("Heart Disease in function of Age and Max Heart Rate")
plt.xlabel("Age")
plt.ylabel("Max Heart Rate")
plt.legend(["Disease", "No Disease"]);

"""**Correlation Matrix\**"""

# Let's make our correlation matrix a little prettier
corr_matrix = df.corr()
fig, ax = plt.subplots(figsize=(15, 15))
ax = sns.heatmap(corr_matrix,
                 annot=True,
                 linewidths=0.5,
                 fmt=".2f",
                 cmap="YlGnBu");
bottom, top = ax.get_ylim()
ax.set_ylim(bottom + 0.5, top - 0.5)

df.drop('target', axis=1).corrwith(df.target).plot(kind='bar', grid=True, figsize=(12, 8),
                                                   title="Correlation with target")

"""### 🔍 Observations from Correlation

* **fbs and chol:**

  * fbs and chol are the least correlated with the target variable.

* **Other variables:**

  * All other variables have a significant correlation with the target variable.

**Data Processing**

After exploring the dataset, we can observe that we need to convert some categorical variables to dummy variables and scale all values before training the machine learning models.
So, for this task, I’ll use the get_dummies method to create dummy columns for categorical variables:
"""

categorical_val.remove('target')
dataset = pd.get_dummies(df, columns = categorical_val)

from sklearn.preprocessing import StandardScaler

s_sc = StandardScaler()
col_to_scale = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
dataset[col_to_scale] = s_sc.fit_transform(dataset[col_to_scale])

"""**Applying Logistic Regression**

Now, I will train a machine learning model for the task of heart disease prediction. I will use the logistic regression algorithm as I mentioned at the beginning of the article.

But before training the model I will first define a helper function for printing the classification report of the performance of the machine learning model:
"""

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

"""Now let’s split the data into training and test sets. I will split the data into 70% training and 30% testing:"""

from sklearn.model_selection import train_test_split

X = dataset.drop('target', axis=1)
y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

"""Now let’s train the machine learning model and print the classification report of our logistic regression model:"""

from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(X_train, y_train)

print_score(lr_clf, X_train, y_train, X_test, y_test, train=True)
print_score(lr_clf, X_train, y_train, X_test, y_test, train=False)

test_score = accuracy_score(y_test, lr_clf.predict(X_test)) * 100
train_score = accuracy_score(y_train, lr_clf.predict(X_train)) * 100

results_df = pd.DataFrame(data=[["Logistic Regression", train_score, test_score]],
                          columns=['Model', 'Training Accuracy %', 'Testing Accuracy %'])
results_df

"""**As you can see the model performs very well of the test set as it is giving almost the same accuracy in the test set as in the training set.**"""